[features]
resolution = true
skip-lint = false

[programs.localnet]
strand_core = "DFb1tb7GHPYaswdhjM2JA4HpHjnCzxJcRZEXzyAvmJ1q"
strand_score = "DF89vhYKM3Rj9KMhWiM2pjdknYrd8YafYq2TBMK6evEA"
strand_credit = "AVSZ1XY45nhYtcqUMUboHhXLLoR2hzSGz95oCRqbyn7x"

[programs.devnet]
strand_core = "DFb1tb7GHPYaswdhjM2JA4HpHjnCzxJcRZEXzyAvmJ1q"
strand_score = "DF89vhYKM3Rj9KMhWiM2pjdknYrd8YafYq2TBMK6evEA"
strand_credit = "AVSZ1XY45nhYtcqUMUboHhXLLoR2hzSGz95oCRqbyn7x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
